- name: flatpak add flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install discord 
  community.general.flatpak:
    name:  com.discordapp.Discord
    state: present
