
- name: flatpak add flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install viber
  community.general.flatpak:
    name:  com.viber.Viber
    state: present
