# Software for development purposes
- name: Install kvm
  include_tasks: kvm/kvm_install.yml

- name: Install Docker
  include_tasks: docker_install.yml
  register: docker_install_result

- name: Install portainer
  include_tasks: portainer_install.yml
  when: docker_install_result is succeeded

- name: Install Helm
  include_tasks: helm_install.yml

- name: Install terraform
  include_tasks: terraform_install.yml

- name: Install minikube
  include_tasks: minikube_install.yml

- name: Install skaffold
  include_tasks: skaffold_install.yml

- name: Install openlens
  include_tasks: openlens_install.yml

- name: compass for mongodb
  include_tasks: compass_install.yml

- name: antaressql for sql databases
  include_tasks: antaressql_install.yml

- name: redis insight
  include_tasks: redisinsight_install.yml

- name: Install postman
  include_tasks: postman_install.yml

- name: Install insomnia
  include_tasks: insomnia_install.yml

- name: Install wireshark
  include_tasks: wireshark_install.yml
  register: wireshark_install_result

- name: Install gns3
  include_tasks: gns3_install.yml
  when: wireshark_install_result is succeeded

- name: Install nvm
  include_tasks: nvm_install.yml

- name: Install VSCode
  include_tasks: vscode_install.yml