
- name: flatpak add flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install obs studio
  community.general.flatpak:
    name:  com.obsproject.Studio
    state: present
